mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    RegistrationView,
    LoginView,
    ProfileView
)


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('reg/', RegistrationView.as_view(), name='reg'),
    path('profile/', ProfileView.as_view(), name='profile')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from django.utils import timezone

User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:

    objects = LatestProductsManager()


class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count'
    }

    def get_queryset(self):
        return super().get_queryset()


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()


class Jacket(Product):

    size = models.CharField(max_length=50, verbose_name='Размер')
    country = models.CharField(max_length=100, verbose_name='Страна происхождения')
    material = models.CharField(max_length=255, verbose_name='Материалы')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_order')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказ',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

mainapp/views.py
from django.db import transaction
from django.shortcuts import render
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, View

from .models import Category, Customer, Cart, CartProduct, Jacket, Order, LatestProducts
from .mixins import CartMixin, CategoryDetailMixin
from .forms import OrderForm, LoginForm, RegistrationForm
from .utils import recalc_cart


class BaseView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        products = LatestProducts.objects.get_products_for_main_page(
            'jacket'
        )
        context = {
            'products': products,
            'cart': self.cart
        }
        return render(request, 'base.html', context)


class ProductDetailView(CartMixin, CategoryDetailMixin, DetailView):

    CT_MODEL_MODEL_CLASS = {
        'jacket': Jacket
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ct_model'] = self.model._meta.model_name
        context['cart'] = self.cart
        return context


class CategoryDetailView(CartMixin, CategoryDetailMixin, DetailView):

    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = self.cart
        return context


class AddToCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product, created = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        if created:
            self.cart.products.add(cart_product)
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар успешно добавлен")
        return HttpResponseRedirect('/cart/')


class DeleteFromCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        self.cart.products.remove(cart_product)
        cart_product.delete()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар успешно удален")
        return HttpResponseRedirect('/cart/')


class ChangeQTYView(CartMixin, View):

    def post(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        qty = int(request.POST.get('qty'))
        cart_product.qty = qty
        cart_product.save()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Кол-во успешно изменено")
        return HttpResponseRedirect('/cart/')


class CartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        context = {
            'cart': self.cart,
        }
        return render(request, 'cart.html', context)


class CheckoutView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        form = OrderForm(request.POST or None)
        context = {
            'cart': self.cart,
            'form': form
        }
        return render(request, 'checkout.html', context)


class MakeOrderView(CartMixin, View):

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST or None)
        customer = Customer.objects.get(user=request.user)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = customer
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.phone = form.cleaned_data['phone']
            new_order.address = form.cleaned_data['address']
            new_order.buying_type = form.cleaned_data['buying_type']
            new_order.order_date = form.cleaned_data['order_date']
            new_order.comment = form.cleaned_data['comment']
            new_order.save()
            self.cart.in_order = True
            self.cart.save()
            new_order.cart = self.cart
            new_order.save()
            customer.orders.add(new_order)
            messages.add_message(request, messages.INFO, 'Спасибо за заказ! Менеджер с Вами свяжется')
            return HttpResponseRedirect('/')
        return HttpResponseRedirect('/checkout/')


class LoginView(CartView, View):
    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        categories = Category.objects.all()
        context = {'form': form, 'categories': categories, 'cart': self.cart}
        return render(request, 'login.html', context)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect('/')
            context = {'form': form, 'cart': self.cart}
            return render(request, 'login.html', context)


class RegistrationView(CartView, View):
    def get(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST or None)
        categories = Category.objects.all()
        context = {'form': form, 'categories': categories, 'cart': self.cart}
        return render(request, 'reg.html', context)

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.username = form.cleaned_data['username']
            new_user.email = form.cleaned_data['email']
            new_user.first_name = form.cleaned_data['first_name']
            new_user.last_name = form.cleaned_data['last_name']
            new_user.save()
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Customer.objects.create(
                user=new_user,
                phone=form.cleaned_data['phone'],
                address=form.cleaned_data['address']
            )
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                login(request, user)
                return HttpResponseRedirect('/')
            context = {'form': form, 'cart': self.cart}
            return render(request, 'reg.html', context)


class ProfileView(CartView, View):

    def get(self, request, *args, **kwargs):
        customer = Customer.objects.get(user=request.user)
        orders = Order.objects.filter(customer=customer).order_by('-created_at')
        categories = Category.objects.all()
        return  render(
            request,
            'profile.html',
            {'orders': orders, 'cart': self.cart}
        )

mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}

{% endblock %}

mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>.
  </title>

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="css/shop-homepage.css" rel="stylesheet">

</head>
<style>
    body {
      padding-top: 56px;
    }
</style>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base' %}">Jackets Shop</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        {% if not request.user.is_authenticated %}
            <li class="navbar-nav">
                <a class="nav-link text-light" href="{% url 'login' %}">Авторизация</a>
            </li>
            <li class="navbar-nav">
                <a class="nav-link text-light" href="{% url 'reg' %}">Регистрация</a>
            </li>
            {% endif %}
            <li class="navbar-nav">
                {% if request.user.is_authenticated %}<span class="navbar text text-light">Привет,&nbsp; <span class="badge badge-light" style="background-color: aliceblue; color: black">
                    <a style="text-decoration: none; font-size: 14px; color: black" href="{% url 'profile' %}">{{ request.user.username }}</a></span>&nbsp;<span class="badge badge-light" style="background-color: aliceblue; color: black"><a style="text-decoration: none; font-size: 14px; color: black"  href="{% url 'logout' %}">Выйти</a></span> </span>{% endif %}
            </li>
      <li class="navbar-nav right" style="margin-left: 800px" >
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-light" style="background-color: aliceblue; color: black">{{ cart.products.count }}</span></a>
          </li>
        </li>
      </div>
    </div>
  </nav>
{% block content %}
  <!-- Page Content -->
  <div class="container">

    <div class="row" style="margin-left: 250px">

      <div class="col-lg-9">

        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
        {% endif %}

        <div class="row">
          {% for product in products %}
          <div class="col-lg-4 mb-4">
            <div class="card h-100 border-0" style="width: 250px">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" style="width: 250px" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}" style="text-decoration: none; color: black">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} ₴</h5>
                <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                  <button class="btn btn-dark">Добавить в корзину</button>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->
      {% endblock content %}
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Просто футер</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <div class="row" style="margin-bottom: 50px;">
    <div class="col-md-8 offset-md-2">
<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
        <th scope="col">Общая цена</th>
      <th scope="col">Действие</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.content_object.title }}</th>
          <td class="w-25"><img src="{{ item.content_object.image.url }}" style="width: 150px; height: 150px" class="img-fluid"></td>
          <td>{{ item.content_object.price }} ₴</td>
          <td>
            <form action="{% url 'change_qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}" method="POST">
              {% csrf_token %}
              <input type="number" class="form-control" name="qty" style="width: 70px;" min="1" value="{{ item.qty }}">
              <br>
              <input type="submit" class="btn btn-secondary" value="Изменить кол-во">
            </form>
          </td>
            <td>{{ item.final_price }} ₴</td>
          <td>
            <a href="{% url 'delete_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}"><button class="btn btn-dark">Удалить из корзины</button></a>
          </td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} ₴</strong></td>
          <td><a href="{% url 'checkout' %}"><button class="btn btn-dark">Оформить заказ</button></a></td>
        </tr>
  </tbody>
</table></div></div>
{% endif %}
{% endblock content %}

mainapp/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row" style="margin-bottom: 300px; margin-top: 100px">
    <div class="col-md-6 offset-md-3">
        <h3>Авторизация</h3>
        <hr>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-secondary" value="Войти">
        </form>
    </div>
</div>

{% endblock %}

mainapp/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="row" style="margin-bottom: 50px; margin-top: 50px" xmlns="http://www.w3.org/1999/html">
    <div class="col-md-6 offset-md-3" style="margin-bottom: 50px;">
        <h3 class="text-center">Информация о пользователе</h3>
    <div class="col-md-5 mt-5" style="width: 600px">
        <p class="card-text"><strong>Логин пользователя:</strong> {{ user.username }}</p>
        <p class="card-text"><strong>Имя:</strong> {{ user.first_name }}</p>
        <p class="card-text"><strong>Фамилия:</strong> {{ user.last_name }}</p>
        <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>
    </div>
<h3 class="text-center">Заказы пользователя <strong>{{ user.username }}</strong></h3>
    {% if not orders.count %}
    <div class="col-md-12 text-center" style="margin-bottom: 100px; margin-top: 200px">
        <h3>У вас ещё нету заказов. <a href="{% url 'base' %}">Начать покупки</a></h3>
    </div>
    {% else %}
    <div class="col-md-12" style="margin-bottom: 200px; margin-top: 100px">
        <table class="table">
            <thead class="table-dark">
                <tr>
                  <th scope="col">Номер</th>
                  <th scope="col">Статус</th>
                  <th scope="col">Сумма</th>
                  <th scope="col">Дополнительно</th>
                </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <th scope="row">{{ order.id }}</th>
                    <td>{{ order.get_status_display }}</td>
                    <td>{{ order.cart.final_price }} ₴</td>

                    <td>
                        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal-{{ order.id }}">
                        Дополнительно
                        </button>
                        <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Детали заказа</h5>
                                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-body">

                                  <table class="table">
                                      <thead class="table-dark">
                                      <tr>
                                         <th scope="col">Наименование</th>
                                          <th scope="col">Изображение</th>
                                          <th scope="col">Цена</th>
                                          <th scope="col">Кол-во</th>
                                          <th scope="col">Общая цена</th>
                                      </tr>
                                      </thead>
                                      <tbody>
                                      {% for item in order.cart.products.all %}
                                        <tr>
                                            <th scope="row">{{ item.content_object.title }}</th>
                                            <td class="w-25"><img src="{{ item.content_object.image.url }}" style="width: 150px; height: 150px" class="img-fluid"></td>
                                            <td>{{ item.content_object.price }} ₴</td>
                                            <td>{{ item.qty }}</td>
                                            <td><strong>{{ item.final_price }}</strong> ₴</td>
                                        </tr>
                                      {% endfor %}
                                      <tr>
                                          <td colspan="2"></td>
                                          <td>Итого: </td>
                                          <td colspan="1"></td>
                                          <td><strong>{{ order.cart.final_price }}</strong> ₴</td>
                                      </tr>
                                      </tbody>
                                  </table>
                              <hr>
                              <h4 class="text-center">Доп. Информация</h4>
                              <p>Имя: <strong>{{ order.first_name }}</strong></p>
                              <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
                              <p>Телефон: <strong>{{ order.phone }}</strong></p>
                              <p>Комментарий к заказу: <strong>{{ order.comment }}</strong></p>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                              </div>
                            </div>
                          </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>{% endif %}
       </div>
</div>
{% endblock %}